config/routes.rb
Rails.application.routes.draw do
  get 'subjects/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :manage do
    resources :accounts do
      collection do
        get :dashboard
      end
      member do
        put :set_current
      end
      resources :teachers
      resources :batches do
        resources :students
      end
      resources :exams do
        resources :papers do
          resources :questions
        end
      end
      resources :subjects do
        resources :topics
      end
    end
  end

  resources :accounts do
    collection do
      get :dashboard
    end
  end
  resources :teachers
  resources :batches do
    resources :students
  end
  resources :exams do
    resources :papers do
      resources :exam_sessions, only: [:create]
    end
  end
  resources :exam_sessions, only: [:index, :show]
  resources :paper_sessions, only: [:index] do
    resources :answers, only: [:new, :create]
  end

  devise_for :teachers, path: :teacher
  devise_for :students, path: :student

  devise_scope :manage do
    authenticated :teacher do
      root 'manage/accounts#dashboard', as: :teacher_root
    end
  end

  root 'accounts#dashboard'
end

app/views/shared/_header.html.haml
.navbar.navbar-inverse.navbar-static-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      %i.fa.fa-graduation-cap
      Examholic
      - if @current_account
        %small{style: "font-size:11px"}= "/ #{@current_account.name}"
    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-nav.pull-right
        %li{:class => ('active' if controller_name == 'accounts' and action_name == 'dashboard')}
          = link_to dashboard_accounts_path do
            %i.fa.fa-home
            Dashboard
        %li{:class => ('active' if controller_name == 'exams' or controller_name == 'papers' or controller_name == 'exam_sessions')}
          = link_to exams_path do
            %i.fa.fa-check-square
            Exams
        %li{:class => ('active' if controller_name == 'batches' or controller_name == 'students')}
          = link_to batches_path do
            %i.fa.fa-users
            Batches
        %li{:class => ('active' if controller_name == 'accounts' and action_name != 'dashboard')}
          = link_to accounts_path do
            %i.fa.fa-bars
            Accounts
        - if student_signed_in?
          %li.dropdown
            = link_to "", :class => "dropdown-toggle", :role => "button", "aria-expanded" => false, :data => {:toggle => "dropdown"} do
              = current_student.name
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                = link_to edit_student_registration_path do
                  %i.fa.fa-user
                  Edit Profile
              %li
                = link_to destroy_student_session_path, :method => :delete do
                  %i.fa.fa-power-off
                  Logout