config/routes.rb
Rails.application.routes.draw do
  get 'subjects/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :manage do
    resources :accounts do
      collection do
        get :dashboard
      end
      member do
        put :set_current
      end
      resources :teachers
      resources :batches do
        resources :students
      end
      resources :exams do
        resources :papers do
          resources :questions
        end
      end
      resources :subjects do
        resources :topics
      end
    end
  end

  resources :accounts do
    collection do
      get :dashboard
    end
  end
  resources :teachers
  resources :batches do
    resources :students
  end
  resources :exams do
    resources :papers do
      resources :exam_sessions, only: [:create]
    end
  end
  resources :exam_sessions, only: [:index, :show]
  resources :paper_sessions, only: [:index] do
    resources :answers, only: [:new, :create]
  end

  devise_for :teachers, path: :teacher
  devise_for :students, path: :student

  devise_scope :manage do
    authenticated :teacher do
      root 'manage/accounts#dashboard', as: :teacher_root
    end
  end

  root 'accounts#dashboard'
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :streams
  has_and_belongs_to_many :subjects
  has_many :account_teachers
  has_many :accounts, :through => :account_teachers
  has_many :admin_accounts, ->{ where('account_teachers.admin = ?', true) }, :through => :account_teachers, :source => :account
  has_many :batches, :through => :accounts

  validates :name, :presence => true
  validates :email, :presence => true
  validates :phone, :presence => true, :numericality => true, :uniqueness => true

  def is_admin? account_id
    AccountTeacher.where(:teacher_id => self.id, :account_id => account_id, :admin => true).exists?
  end
end

app/controllers/student/teachers_controller.rb
class Student::TeachersController < Student::ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  def index
    @teachers = @account.teachers.all
  end

  def show
  end

  def new
    @teacher = Teacher.new
  end

  private
    def set_teacher
      @teacher = Teacher.where(:id => params[:id]).first
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_student!
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  def index
    @teachers = @account.teachers.all
  end

  def show
  end

  def new
    @teacher = Teacher.new
  end

  private
    def set_teacher
      @teacher = Teacher.where(:id => params[:id]).first
    end
end

app/views/teachers/index.html.haml
%div
  %h6.text-uppercase.pull-left= @account.name
  %p.pull-right
    = link_to new_manage_account_teacher_path(@account), class: "btn btn-default btn-sm" do
      %i.fa.fa-plus
      Add
  .clearfix
%table.table
  %thead
    %tr
      %th Name
      %th Email
      %th Phone
      %th Admin
      %th Actions

  %tbody
    - @teachers.each do |teacher|
      %tr
        %td= teacher.name
        %td= teacher.email
        %td= '******'+teacher.phone[-4..-1].to_s
        %td
          - is_admin = teacher.is_admin?(@account.id)
          = link_to manage_account_teacher_path(@account, teacher.id), method: :put, data: {confirm: "Are you sure?"} do
            %span.label{:class => (is_admin ? 'label-primary' : 'label-default') }= is_admin ? "Yes" : "No"
        %td= link_to 'Remove', manage_account_teacher_path(@account, teacher), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-xs"
%br

app/views/teachers/show.html.haml
%p#notice= notice