config/routes.rb
Rails.application.routes.draw do
  get 'subjects/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :manage do
    resources :accounts do
      collection do
        get :dashboard
      end
      member do
        put :set_current
      end
      resources :teachers
      resources :batches do
        resources :students
      end
      resources :exams do
        resources :papers do
          resources :questions
        end
      end
      resources :subjects do
        resources :topics
      end
    end
  end

  resources :accounts do
    collection do
      get :dashboard
    end
  end
  resources :teachers
  resources :batches do
    resources :students
  end
  resources :exams do
    resources :papers do
      resources :exam_sessions, only: [:create]
    end
  end
  resources :exam_sessions, only: [:index, :show]
  resources :paper_sessions, only: [:index] do
    resources :answers, only: [:new, :create]
  end

  devise_for :teachers, path: :teacher
  devise_for :students, path: :student

  devise_scope :manage do
    authenticated :teacher do
      root 'manage/accounts#dashboard', as: :teacher_root
    end
  end

  root 'accounts#dashboard'
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  has_and_belongs_to_many :batches
  has_and_belongs_to_many :segments
  has_many :exam_sessions
  has_many :papers
  belongs_to :account
  belongs_to :batch

  validates :name, :presence => true
  validates :account_id, :presence => true
  validates :batch_id, :presence => true
  validates :duration, :presence => true
  validates :start_time, :presence => true
  validates :end_time, :presence => true
  
  paginates_per 4

  scope :live, ->{ where('start_time <= ? and end_time > ?', Time.zone.now, Time.zone.now) }

  def live?
    start_time <= Time.zone.now and end_time > Time.zone.now
  end

  def expired?
    end_time <= Time.zone.now
  end

  def upcoming?
    start_time > Time.zone.now
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :authenticate_student!
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = current_student.exams.page(params[:page])
    @finished_exam_ids = ExamSession.where.not(finished_at: nil).where(student_id: current_student.id).pluck(:exam_id)
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = current_student.exams.where(:id => params[:id]).first
    end
end

app/controllers/student/exams_controller.rb
class Student::ExamsController < Student::ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = current_student.exams.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = current_student.exams.where(:id => params[:id]).first
    end
end

app/views/exams/index.html.haml
%h2 Exams
%table.table.table-condensed
  %tbody
    - @exams.each do |exam|
    - @exam_session = ExamSession.find_by(exam_id: exam.id,student_id: current_student.id)
      %tr
        %td
          %h4= link_to "#{exam.name}", exam_papers_path(exam)
          - if @finished_exam_ids.include?(exam.id)
            %cite= link_to 'View Results', exam_papers_path(exam)
            %cite= link_to 'View Rankings', exam_session_path(exam)
          - elsif exam.live?
            %cite= link_to 'Begin Exam', exam_papers_path(exam)
        %td.text-right
          %h4= link_to exam.papers.count, exam_papers_path(exam)
          %cite Papers
        %td.text-right
          %h4= distance_of_time_in_words(exam.start_time, exam.end_time)
          %cite Duration
        %td.text-right
          %h4= exam.batch.name
          %cite Batch
        %td.text-right
          %h4= exam.account.name
          %cite Institute
        - if @exam_session.blank?
          %td.text-right
            %h4= "-"
            %cite Score
          %td.text-right
            %h4= "-"
            %cite Percentage
          %td.text-right
            %h4= "-"
            %cite Maximum Marks
        - else
          %td.text-right
            %h4= @exam_session.score
            %cite Score
          %td.text-right
            %h4= @exam_session.percentage.to_s + "%"
            %cite Percentage
          %td.text-right
            %h4= @exam_session.max_marks
            %cite Maximum Marks
        - if exam.expired?
          %td.text-right
            %h4= distance_of_time_in_words_to_now(exam.end_time) + ' ago'
            %cite Finished
        - elsif exam.upcoming?
          %td.text-right
            %h4= distance_of_time_in_words_to_now exam.start_time
            %cite Starts In
        - elsif exam.live?
          %td.text-right
            %h4= distance_of_time_in_words_to_now(exam.end_time)
            %cite Finishes In

app/views/exams/show.html.haml
- model_class = Exam
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:account_id) + ':'
  %br
  = @exam.account_id
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @exam.name
%p
  %strong= model_class.human_attribute_name(:status) + ':'
  %br
  = @exam.status
%p
  %strong= model_class.human_attribute_name(:duration) + ':'
  %br
  = @exam.duration
%p
  %strong= model_class.human_attribute_name(:start_time) + ':'
  %br
  = @exam.start_time
%p
  %strong= model_class.human_attribute_name(:end_time) + ':'
  %br
  = @exam.end_time


= link_to t('.back', :default => t("helpers.links.back")), manage_account_exams_path(@current_account), :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_manage_account_exam_path(@current_account, @exam), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), manage_account_exam_path(@current_account, @exam), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'